# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    # Run setup_ci for any CI environment
    setup_ci if ENV['CI']
    #is_ci? 
    match(type: 'appstore')
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do

    #setup_ci if ENV['CI']
    #match(type: 'appstore')
    increment_build_number(xcodeproj: "homework6.xcodeproj")
    

    api_key = app_store_connect_api_key(
        key_id: ENV['FASTLANE_APPLE_KEY_ID'],
        issuer_id: ENV['FASTLANE_APPLE_ISSUER_ID'],
        key_content: ENV['FASTLANE_APPLE_KEY_CONTENT'] # Or key_filepath: ENV['FASTLANE_APPLE_KEY_FILEPATH']
      )
    build_app(scheme: "homework6")
    upload_to_testflight(
        api_key: api_key,
      skip_waiting_for_build_processing: true # Don't wait for processing on CI
    )
  end
end
