name: Google Cloud secrets extract

permissions:
      contents: write
      pull-requests: write
      id-token: write

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_PROVIDER }}

      # Step 2: Extract the project ID
      - name: Extract project ID
        id: extract
        env:
          SERVICE_ACCOUNT_EMAIL: ${{ secrets.WIF_PROVIDER }}
        run: |
          PROJECT_ID=${SERVICE_ACCOUNT_EMAIL#*@}
          PROJECT_ID=${PROJECT_ID%.iam.gserviceaccount.com}
          echo "project_id=$PROJECT_ID" >> "$GITHUB_OUTPUT"

      # Step 3: Construct the secrets list in a variable
      # This avoids parsing issues by preparing the input as a single variable.
      - name: Prepare secrets input
        id: prepare_secrets
        run: |
          SECRETS_INPUT=$(cat <<-END
            MY_SECRET: projects/${{ steps.extract.outputs.project_id }}/secrets/APP_STORE_CONNECT_API_KEY_ISSUER_ID/versions/latest
            ANOTHER_SECRET: projects/${{ steps.extract.outputs.project_id }}/secrets/APP_STORE_CONNECT_API_KEY_KEY_ID/versions/latest
          END
          )
          echo "secrets_input=$SECRETS_INPUT" >> "$GITHUB_OUTPUT"

      # Step 4: Get secrets from Secret Manager using the prepared variable
      - name: Get secrets from Secret Manager
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: ${{ steps.prepare_secrets.outputs.secrets_input }}
      
      # Step 5: Use the fetched secrets
      - name: Use secrets
        run: |
          echo "My secret is: ${{ steps.get-secrets.outputs.MY_SECRET }}"
          echo "Another secret is: ${{ steps.get-secrets.outputs.ANOTHER_SECRET }}"
