name: Google Cloud secrets extract

permissions:
      contents: write
      pull-requests: write
      id-token: write

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Extract project ID from secret
        id: extract
        env:
          SERVICE_ACCOUNT_EMAIL: ${{ secrets.WIF_PROVIDER }}
        run: |
          # Use shell parameter expansion to remove the prefix and suffix
          PROJECT_ID=${SERVICE_ACCOUNT_EMAIL#*@}
          PROJECT_ID=${PROJECT_ID%.iam.gserviceaccount.com}
          
          # Print the extracted ID for verification.
          # Note: The secret value is automatically masked in logs.
          echo "Extracted project ID: $PROJECT_ID"
          echo "$PROJECT_ID" | sed 's/./& /g'
          
          # Set the project ID as a step output for use in other steps
          echo "project_id=$PROJECT_ID" >> "$GITHUB_OUTPUT"

      - name: Use the extracted project ID
        run: |
          echo "The project ID is ${{ steps.extract.outputs.project_id }}"

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }} # GitHub secret for your Workload Identity Provider URL
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }} # GitHub secret for your Service Account email

      - name: Get secrets from Secret Manager
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |
            MY_SECRET: 'projects/${{ steps.extract.outputs.project_id }}/secrets/APP_STORE_CONNECT_API_KEY_ISSUER_ID/versions/latest'
            ANOTHER_SECRET: 'projects/${{ steps.extract.outputs.project_id }}/secrets/APP_STORE_CONNECT_API_KEY_KEY_ID/versions/latest'

      - name: Use secrets
        run: |
          echo "My secret value: ${{ steps.get-secrets.outputs.MY_SECRET }}"
          echo "Another secret value: ${{ steps.get-secrets.outputs.ANOTHER_SECRET }}"



